# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: setup-Redhat | DNF - Install Pyroscope from remote URL
  ansible.builtin.dnf:
    name: "{{ mimir_download_url_rpm }}"
    state: present
    disable_gpg_check: true
  notify: Restart pyroscope
  when: __current_deployed_version.stdout is not defined or pyroscope_version not in __current_deployed_version.stdout
