# SPDX-FileCopyrightText: 2024 Weytop
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import gpg tasks
  ansible.builtin.import_tasks: gpg.yml
  when: aptly_gpg_private_key and aptly_gpg_public_key and aptly_gpg_fpr

- name: Import repository tasks
  ansible.builtin.import_tasks: repository.yml
  when: aptly_repositories | default([]) | length > 0
