# SPDX-FileCopyrightText: 2024 Weytop
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: mirror | Trust gpg keys for mirroring
  block:
    - name: mirror | Download public keys
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "/etc/apt/keyrings/{{ item.name }}"
        mode: "0644"
      when: item.state is not defined or item.state == 'present'
      with_items: "{{ aptly_mirrors_keys_urls }}"
      
    - name: mirror | Remove public keys
      ansible.builtin.file:
        path: "/etc/apt/keyrings/{{ item.name }}"
        state: absent
      when: item.state is defined and item.state == 'absent'
      with_items: "{{ aptly_mirrors_keys_urls }}"

    - name: mirror | Import mirrors trusted keys
      weytop.infrastructure.gpg_key:
        file: "/etc/apt/keyrings/{{ item.name }}"
        keyring: "{{ aptly_home }}/.gnupg/trustedkeys.gpg"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ aptly_mirrors_keys_urls }}"
      become: true
      become_user: "{{ aptly_user }}"

- name: mirror | Create mirrors
  weytop.infrastructure.aptly_mirror:
    endpoint: "http://{{ aptly_listen }}"
    name: "{{ item.name }}"
    archive_url: "{{ item.archive_url }}"
    distribution: "{{ item.distribution }}"
    components: "{{ item.components }}"
    architectures: "{{ item.architectures }}"
    download_sources: "{{ item.download_sources | default(false) }}"
    download_installer: "{{ item.download_installer | default(false) }}"
    sync: "{{ item.sync | default(false) }}"
    force: "{{ item.force | default(false) }}"
  with_items: "{{ aptly_mirrors }}"
