# SPDX-FileCopyrightText: 2024 Weytop
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: repository | Create repositories
  weytop.infrastructure.aptly_repository:
    endpoint: "http://{{ aptly_listen }}"
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    distribution: "{{ item.distribution }}"
    component: "{{ item.component | default('main') }}"
  with_items: "{{ aptly_repositories }}"
