---
galaxy_info:
  author: Antoine Thys
  description: Add certificate files to use with Nginx
  company: Weytop

  license: GPL-3.0-or-later

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - certificates
    - nginx
    - ubuntu

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
