---
- name: setup | Install dependencies
  ansible.builtin.apt:
    name: "{{ influxdb_dependencies }}"
    state: present
    update_cache: true

- name: setup | Add InfluxData's key
  ansible.builtin.apt_key:
    state: present
    url: "{{ influxdb_signing_key }}"

- name: setup | Manage InfluxData APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ influxdb_repositories }}"

- name: setup | Ensure InfluxDB packages are installed | Apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ influxdb_package_state }}"
    update_cache: true
  loop: "{{ influxdb_packages }}"

- name: setup | Setup InfluxDB default file
  ansible.builtin.template:
    dest: /etc/default/influxdb2
    group: root
    mode: "0644"
    owner: root
    src: etc/default/influxdb2.j2
  notify: Restart InfluxDB

- name: setup | Create influxdb system group
  ansible.builtin.group:
    name: influxdb
    system: true
    state: present

- name: setup | Create influxdb system user
  ansible.builtin.user:
    name: influxdb
    system: true
    shell: "/usr/sbin/nologin"
    group: influxdb

- name: setup | Ensure InfluxDB directories exist
  ansible.builtin.file:
    group: influxdb
    mode: "0750"
    owner: influxdb
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ influxdb_config_path }}"
    - "{{ influxdb_bolt_path | dirname }}"
    - "{{ influxdb_engine_path }}"

- name: setup | Remove any previous InfluxDB configuration file
  ansible.builtin.file:
    path: "{{ influxdb_config_path }}/{{ item }}"
    state: absent
  loop:
    - config.json
    - config.toml
  notify: Restart InfluxDB

- name: setup | Setup InfluxDB configuration file
  ansible.builtin.template:
    dest: "{{ influxdb_config_path }}/config.yml"
    group: influxdb
    mode: "0644"
    owner: influxdb
    src: etc/influxdb/config.yml.j2
  notify: Restart InfluxDB

- name: setup | Ensure InfluxDB service is in the desired state
  ansible.builtin.service:
    enabled: "{{ influxdb_service_enabled }}"
    name: "{{ influxdb_service_name }}"
    state: "{{ influxdb_service_state }}"
