# SPDX-FileCopyrightText: 2024 Weytop
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Infrastructure Collection for Ansible"
SPDX-PackageSupplier = "Weytop <contact@weytop.com>"
SPDX-PackageDownloadLocation = "https://github.com/weytop/ansible-infrastructure-collection"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "roles/**/tests/inventory"
precedence = "override"
SPDX-FileCopyrightText = "2024 Weytop"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "poetry.*"
precedence = "override"
SPDX-FileCopyrightText = "2024 Weytop"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "pyproject.toml"
precedence = "override"
SPDX-FileCopyrightText = "2024 Weytop"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CHANGELOG.md"
precedence = "override"
SPDX-FileCopyrightText = "2024 Weytop"
SPDX-License-Identifier = "CC0-1.0"
