---
galaxy_info:
  author: Antoine Thys
  description: Install and configure InfluxDB
  company: Weytop

  license: GPL-3.0-or-later

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - influxdb

dependencies: []
