# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
tempo_version: "latest"
__tempo_arch: "{{ tempo_arch_mapping[ansible_architecture] | default('amd64') }}"
tempo_download_url_rpm: "https://github.com/grafana/tempo/releases/download/v{{ tempo_version }}/tempo_{{ tempo_version }}_linux_{{ __tempo_arch }}.rpm"
tempo_download_url_deb: "https://github.com/grafana/tempo/releases/download/v{{ tempo_version }}/tempo_{{ tempo_version }}_linux_{{ __tempo_arch }}.deb"

tempo_working_path: "/var/tempo"
tempo_http_listen_port: 3200
tempo_http_listen_address: "0.0.0.0"
tempo_log_level: warn

tempo_multitenancy_enabled: false

tempo_stream_over_http_enabled: true

tempo_usage_report: true

tempo_query_frontend:
  search:
    duration_slo: 5s
  trace_by_id:
    duration_slo: 5s

tempo_distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

tempo_ingester:
  max_block_duration: 30m

tempo_compactor:
  compaction:
    block_retention: 336h

tempo_metrics_generator:

tempo_storage:
  trace:
    backend: local
    wal:
      path: "{{ tempo_working_path }}/wal"
    local:
      path: "{{ tempo_working_path }}/blocks"

tempo_server:
  http_listen_port: "{{ tempo_http_listen_port }}"
  http_listen_address: "{{ tempo_http_listen_address }}"
  log_level: "{{ tempo_log_level }}"

tempo_overrides:
  defaults:
    metrics_generator:
