galaxy_info:
  author: Antoine Thys
  description: Install and configure the Minio S3 compatible object storage server Debian/Ubuntu
  company: Weytop

  license: GPL-3.0-or-later

  min_ansible_version: '2.1'

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - system
    - minio
    - storage
    - objectstorage
    - s3

dependencies: []
