# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
# tasks file for op-to-file
- name: Get secret from 1password
  onepassword.connect.item_info:
    token: "{{ onepassword_token }}"
    hostname: "{{ onepassword_hostname }}"
    vault: "{{ onepassword_vault_id }}"
    item: "{{ get_1password_ca_item }}"
  no_log: true
  register: item_info
  delegate_to: "{{ get_1password_ca_delegate_to }}"
  delegate_facts: false
  become: "{{ get_1password_ca_become }}"
  become_user: "{{ get_1password_ca_become_user }}"
  tags:
    - 1password
    - get-1password-ca

- name: Write public key to file
  ansible.builtin.copy:
    content: "{{ item_info.op_item.fields.public_key.value }}"
    dest: "{{ get_1password_ca_public_key_file }}"
    mode: "0600"
  delegate_to: "{{ get_1password_ca_delegate_to }}"
  delegate_facts: false
  become: "{{ get_1password_ca_become }}"
  become_user: "{{ get_1password_ca_become_user }}"
  tags:
    - 1password
    - get-1password-ca

- name: Write private key to file
  ansible.builtin.copy:
    content: "{{ item_info.op_item.fields.private_key.value }}"
    dest: "{{ get_1password_ca_private_key_file }}"
    mode: "0600"
  delegate_to: "{{ get_1password_ca_delegate_to }}"
  delegate_facts: false
  become: "{{ get_1password_ca_become }}"
  become_user: "{{ get_1password_ca_become_user }}"
  tags:
    - 1password
    - get-1password-ca

- name: Set facts with private key password
  ansible.builtin.set_fact:
    get_1password_ca_private_key_password: "{{ item_info.op_item.fields.password.value }}"
  delegate_to: "{{ get_1password_ca_delegate_to }}"
  delegate_facts: false
  become: "{{ get_1password_ca_become }}"
  become_user: "{{ get_1password_ca_become_user }}"
  no_log: true
  tags:
    - 1password
    - get-1password-ca
