---
# tasks file for op-to-file
- name: Get secret from 1password
  onepassword.connect.item_info:
    token: "{{ onepassword_token }}"
    hostname: "{{ onepassword_hostname }}"
    vault: "{{ onepassword_vault_id }}"
    item: "{{ onepassword_ca_item }}"
  no_log: true
  register: item_info
  tags:
    - 1password
    - get-1password-ca

- name: Write public key to file
  ansible.builtin.copy:
    content: "{{ item_info.op_item.fields.public_key.value }}"
    dest: "{{ onepassword_ca_public_key_file }}"
    mode: '0600'
  tags:
    - 1password
    - get-1password-ca

- name: Write private key to file
  ansible.builtin.copy:
    content: "{{ item_info.op_item.fields.private_key.value }}"
    dest: "{{ onepassword_ca_private_key_file }}"
    mode: '0600'
  tags:
    - 1password
    - get-1password-ca

- name: Set facts with private key password
  ansible.builtin.set_fact:
    onepassword_ca_private_key_password: "{{ item_info.op_item.fields.password.value }}"
  tags:
    - 1password
    - get-1password-ca
