---
# handlers file for ca-certificates
- name: Write fullchain certificate
  ansible.builtin.copy:
    dest: "{{ ca_certificates_fullchain }}"
    content: |-
      {{ ca_certificate.certificate | trim }}
      {{ lookup('file', ca_certificates_ca_cert) | trim }}
    mode: "{{ ca_certificates_cert_permissions }}"
    owner: "{{ ca_certificates_cert_owner }}"
    group: "{{ ca_certificates_cert_group }}"
  tags:
    - ca-certificates
    - ca-certificates-certificate-fullchain-write

- name: Write certificate
  ansible.builtin.copy:
    dest: "{{ ca_certificates_cert }}"
    content: "{{ ca_certificate.certificate }}"
    mode: "{{ ca_certificates_cert_permissions }}"
    owner: "{{ ca_certificates_cert_owner }}"
    group: "{{ ca_certificates_cert_group }}"
  tags:
    - ca-certificates
    - ca-certificates-certificate-write
