# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Add Knot Resolver repository
  block:
    - name: Get Knot Resolver Key
      ansible.builtin.get_url:
        url: "{{ knot_gpg_key_url }}"
        dest: "{{ knot_resolver_gpg_key }}"
        mode: "0644"
        owner: root
        group: root
    - name: Add Knot Resolver repository
      ansible.builtin.apt_repository:
        repo: "{{ knot_resolver_repo }}"
        state: present
        filename: knot-resolver
        update_cache: true

- name: Install Knot
  ansible.builtin.apt:
    name:
      - knot
      - knot-dnsutils
      - knot-dnssecutils
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set Knot TSIG Key fact
  ansible.builtin.set_fact:
    knot_tsig_key_secret: "{{ knot_tsig_key_secret }}"
    knot_admin_key_secret: "{{ knot_admin_key_secret }}"
  delegate_to: localhost
  run_once: true

- name: Template Knot configuration
  ansible.builtin.template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart Knot

- name: Enable Knot Service
  ansible.builtin.systemd:
    name: knot.service
    enabled: true
    masked: false
    state: started
