# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---

# Minio binaries path
minio_server_bin: /usr/local/bin/minio
minio_client_bin: /usr/local/bin/mc

# Minio release to install. default if lastet
minio_server_release: ""
minio_client_release: ""

# Runtime user and group for the Minio server service
minio_user: minio
minio_group: minio
minio_usergroup_manage: true

# Path to the file containing the ENV variables for the Minio server
minio_server_envfile: /etc/default/minio

# Minio server ip/fqdn and port. This makes up the server_addr below
minio_server_ip: ""
minio_server_port: "9000"

# Minio server listen address
minio_server_addr: "{{ minio_server_ip }}:{{ minio_server_port }}"

# Minio console ip/fqdn and port. This makes up the console_addr below
minio_console_ip: ""
minio_console_port: "9001"

# Minio console listen address
minio_console_addr: "{{ minio_console_ip }}:{{ minio_console_port }}"

# Minio URL for access from the console
minio_server_url: ""

# Minio URL for access console from the browser
minio_browser_redirect_url: ""

# Minio server data directories
minio_server_datadirs:
  - /var/lib/minio
minio_server_make_datadirs: true

# Minio server cluster node list.
minio_server_cluster_nodes: []

# Additional environment variables to be set in minio server environment
minio_server_env_extra: ""

# Additional Minio server CLI options
minio_server_opts: ""

# Directory to store minio config. Will default to minio_user/.minio if not defined
minio_config_dir: ""

# Minio root user credentials
minio_root_user: ""
minio_root_password: ""

# Switches to enable/disable the Minio server and/or Minio client installation.
minio_install_server: true
minio_configure_server: true
minio_install_client: true

# Switches Minio installation source: allowed is one of ['download', 'repo']
minio_install_source: download

# Update Minio when installed from repo
minio_upgrade: true

# Minio region
minio_region: us-east-1
