---
# defaults file for get_1password_ca
get_1password_ca_item:
get_1password_ca_public_key_file: "{{ playbook_dir }}/files/ca/ca.pem"
get_1password_ca_private_key_file: "{{ playbook_dir }}/files/ca/ca.key"

get_1password_ca_delegate_to: localhost
get_1password_ca_become: false
get_1password_ca_become_user: root
