# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# TODO: Switch to dnssec
knot_zones:
  - domain: weytop.net
    template: default
  - domain: weytop.local
    template: default
  - domain: 10.in-addr.arpa
    template: default

knot_listen:
  - "{{ ansible_host }}@5353"
  - 127.0.0.53@53

knot_tsig_key_secret:
knot_admin_key_secret:
