# SPDX-FileCopyrightText: 2024 Weytop
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
# User running aptly api service
aptly_user: aptly
# Group running aptly api service
aptly_group: aptly
# Home directory of aptly user
aptly_home: /var/lib/aptly

# Aptly api listen address
aptly_listen: 127.0.0.1:8000

# Aptly configuration template file as yaml dictionary and convert to nice json format
# See https://www.aptly.info/doc/configuration/ for configuration options
aptly_json_config:
  rootDir: "{{ aptly_home }}/repos"
  downloadConcurrency: 4
  downloadSpeedLimit: 0
  architectures: [amd64]
  dependencyFollowSuggests: false
  dependencyFollowRecommends: false
  dependencyFollowAllVariants: false
  dependencyFollowSource: false
  dependencyVerboseResolve: false
  gpgDisableSign: false
  gpgDisableVerify: false
  gpgProvider: "gpg"
  downloadSourcePackages: false
  skipLegacyPool: true
  ppaDistributorID: "{{ ansible_distribution }}"
  ppaCodename: "{{ ansible_distribution_release }}"

  FileSystemPublishEndpoints:
    local:
      rootDir: "/srv/aptly/local"
      linkMethod: "copy"
      verifyMethod: "md5"
  S3PublishEndpoints: {}
  SwiftPublishEndpoints: {}

  enableMetricsEndpoint: true
  logLevel: "info"
  logFormat: "default"
  serveInAPIMode: true

# GPG Private key content to import into aptly user keyring
aptly_gpg_private_key: ""
# GPG Public key content to import into aptly user keyring
aptly_gpg_public_key: ""
# Fingerprint of GPG public key to trust
aptly_gpg_fpr: ""

# List of repositories to create
aptly_repositories: []
  # - name: app_testing
  #   comment: App Nightly builds
  #   distribution: noble
  #   component: testing (main if not specified)
  # - name: app_stable
  #   comment: App Stable builds
  #   distribution: noble
