# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---

- name: Reload minio systemd
  ansible.builtin.systemd:
    name: minio
    daemon_reload: true

- name: Restart minio
  ansible.builtin.service:
    name: minio
    state: restarted
