# SPDX-FileCopyrightText: 2024 ThysTips <contact@thystips.net>
# SPDX-FileCopyrightText: 2024 Weytop
# SPDX-FileContributor: ThysTips <contact@thystips.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: dependencies | Import Get CA
  ansible.builtin.import_role:
    name: get_1password_ca
  vars:
    get_1password_ca_item: "{{ ca_certificates_ca_1password_item }}"
    get_1password_ca_delegate_to: "{{ ca_certificates_ca_host }}"
    get_1password_ca_become: "{{ ca_certificates_ca_become }}"
    get_1password_ca_become_user: "{{ ca_certificates_ca_become_user }}"
  when: (get_1password_ca_public_key_file is not defined
    or get_1password_ca_private_key_file is not defined
    or get_1password_ca_private_key_password is not defined)
    and ca_certificates_ca_1password_item is defined
  tags:
    - get-1password-ca
    - ca-certificates
    - ca-certificates-dependencies

- name: dependencies | Import Trust CA
  ansible.builtin.import_role:
    name: trust_ca
  tags:
    - trust-ca
    - ca-certificates
    - ca-certificates-dependencies

- name: dependencies | Import Create folders
  ansible.builtin.include_role:
    name: create_folder
    apply:
      tags:
        - create-folder
        - ca-certificates
        - ca-certificates-dependencies
  # vars:
  #   create_folder_path: "{{ item }}"
  loop:
    - "{{ ca_certificates_cert | dirname }}"
    - "{{ ca_certificates_full_chain | dirname }}"
    - "{{ ca_certificates_key | dirname }}"
  loop_control:
    loop_var: create_folder_path
  tags:
    - create-folder
    - ca-certificates
    - ca-certificates-dependencies
